AWSTemplateFormatVersion: 2010-09-09
Description: Template for s3 bucket

Parameters:
  Project:
    Description: Project name
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Stage:
    Description: Stage name
    Type: String
    Default: dev
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{2,15}$
  BucketName:
    Description: Name of the bucket
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Project}-${Stage}-${BucketName}-bucket

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: S3 Bucket bucket name
